### ISSUE TITLE
when I import llama-index,arise problem 'no module named openai.openai_object' 

### ISSUE THREAD

**Issue by cementwise** [marklysze/LlamaIndex-RAG-WSL-CUDA#2]
![47b899e33256a90894c1aa19a9eea0c](https://github.com/marklysze/LlamaIndex-RAG-WSL-CUDA/assets/107919397/50f37f47-3257-44c4-8b62-c329281862a7)
![eccb143d117e21686883fa190fdd51b](https://github.com/marklysze/LlamaIndex-RAG-WSL-CUDA/assets/107919397/b8a73a1f-2f98-46cd-865d-2a18709c66d3)

**Comment by marklysze** [comment]
Hi @cementwise, looking on llamaindex's repo, seems like it may be a python 3.12+ issue. If you're not on 3.12 or above let me know. 

Llamaindex issue:
https://github.com/run-llama/llama_index/issues/9292

This repo has an conda environment with 3.11. 

The issue has been rectified in llamaindex so I'll update this repo to python 3.12. I'll do that shortly and update the issue. 

Thanks for logging the issue.

**Comment by marklysze** [comment]
@cementwise, unfortunately pytorch is not compatible with python 3.12. Track issue [here](https://github.com/pytorch/pytorch/issues/110436)

They've put it into a pytorch v2 milestone which has a Jan 31 target date. When it is available I can try again to update the repository to python 3.12.

For now, you may need to create a new conda environment with python 3.11:
`conda create -n LlamaIndexGeneric python=3.11`

Then follow through with installation of the other pip packages, CUDA, etc.

**Comment by marklysze** [comment]
Closing now. If pytorch v2 is released and supports Python 3.12 I can update the notebooks then.

**Comment by alecthekulak** [comment]
I'm seeing `ModuleNotFoundError: No module named 'openai.openai_object'` even with Python version 3.11.5, so this issue does not appear to be restricted to Python 3.12

![image](https://github.com/marklysze/LlamaIndex-RAG-WSL-CUDA/assets/5726079/6776ad8b-64fe-4dfc-9a75-7ac8dfa59c61)
